application: nathansjslessons
version: 2
runtime: python
api_version: 1

handlers:
- url: /gfx
  static_dir: gfx
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: .*
  script: main.py

builtins:
- remote_api: on
